#define SHAPE_SHIFT  11
#define SHAPE_SCALAR (0x0UL << SHAPE_SHIFT)
#define SHAPE_1DVEC  (0x4UL << SHAPE_SHIFT)

#define REPRE_SHIFT  6
#define REPRE_UNSIGN (0x0UL << REPRE_SHIFT)
#define REPRE_SIGNED (0x1UL << REPRE_SHIFT)
#define REPRE_FPOINT (0x3UL << REPRE_SHIFT)

#define BWIDTH_SHIFT 0
#define BWIDTH_8B    (0x8UL  << BWIDTH_SHIFT)
#define BWIDTH_16B   (0x10UL << BWIDTH_SHIFT)
#define BWIDTH_32B   (0x18UL << BWIDTH_SHIFT)
#define BWIDTH_64B   (0x20UL << BWIDTH_SHIFT)

#define V_UINT8      (SHAPE_1DVEC  | REPRE_UNSIGN | BWIDTH_8B)
#define S_UINT8      (SHAPE_SCALAR | REPRE_UNSIGN | BWIDTH_8B)
#define V_INT8       (SHAPE_1DVEC  | REPRE_SIGNED | BWIDTH_8B)
#define S_INT8       (SHAPE_SCALAR | REPRE_SIGNED | BWIDTH_8B)

#define V_UINT16     (SHAPE_1DVEC  | REPRE_UNSIGN | BWIDTH_16B)
#define S_UINT16     (SHAPE_SCALAR | REPRE_UNSIGN | BWIDTH_16B)
#define V_INT16      (SHAPE_1DVEC  | REPRE_SIGNED | BWIDTH_16B)
#define S_INT16      (SHAPE_SCALAR | REPRE_SIGNED | BWIDTH_16B)
#define V_FP16       (SHAPE_1DVEC  | REPRE_FPOINT | BWIDTH_16B)
#define S_FP16       (SHAPE_SCALAR | REPRE_FPOINT | BWIDTH_16B)

#define V_UINT32     (SHAPE_1DVEC  | REPRE_UNSIGN | BWIDTH_32B)
#define S_UINT32     (SHAPE_SCALAR | REPRE_UNSIGN | BWIDTH_32B)
#define V_INT32      (SHAPE_1DVEC  | REPRE_SIGNED | BWIDTH_32B)
#define S_INT32      (SHAPE_SCALAR | REPRE_SIGNED | BWIDTH_32B)
#define V_FP32       (SHAPE_1DVEC  | REPRE_FPOINT | BWIDTH_32B)
#define S_FP32       (SHAPE_SCALAR | REPRE_FPOINT | BWIDTH_32B)

#define V_UINT64     (SHAPE_1DVEC  | REPRE_UNSIGN | BWIDTH_64B)
#define S_UINT64     (SHAPE_SCALAR | REPRE_UNSIGN | BWIDTH_64B)
#define V_INT64      (SHAPE_1DVEC  | REPRE_SIGNED | BWIDTH_64B)
#define S_INT64      (SHAPE_SCALAR | REPRE_SIGNED | BWIDTH_64B)
#define V_FP64       (SHAPE_1DVEC  | REPRE_FPOINT | BWIDTH_64B)
#define S_FP64       (SHAPE_SCALAR | REPRE_FPOINT | BWIDTH_64B)
